[package]
name = "offchain_impl"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = { version = "1.6.0", features = ["derive"] }
redis = "1.0.2"
sha256 = "1.6.0"
spl-concurrent-merkle-tree = "1.0.0"
